# Generated by Django 4.0.10 on 2023-08-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Museum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Name')),
                ('description', models.TextField(default='Description...', verbose_name='Description')),
                ('category', models.CharField(max_length=25, verbose_name='Category')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('contact', models.CharField(max_length=12, verbose_name='Contact')),
                ('email', models.EmailField(max_length=50, verbose_name='Emsil')),
                ('working_mode', models.DateTimeField(verbose_name='Working mode')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Title',
                'verbose_name_plural': 'Titles',
            },
        ),
    ]
