# Generated by Django 4.0.10 on 2023-08-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museum',
            name='address',
            field=models.CharField(max_length=50, verbose_name='Address of museum'),
        ),
        migrations.AlterField(
            model_name='museum',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='museum',
            name='title',
            field=models.CharField(max_length=25, verbose_name='Name of museum'),
        ),
    ]
